'use client'

import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react'

type Language = 'en' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // TopNav tabs
    "nav.dashboard": "Dashboard",
    "nav.opportunities": "Opportunities",
    "nav.application": "Application",
    "nav.profile": "Profile",
    "nav.account": "Account",
    "nav.settings": "Settings",
    "nav.language": "Language",
    "nav.signOut": "Sign out",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.matchesFound": "Matches Found",
    "dashboard.outreachSent": "Outreach Sent",
    "dashboard.responsesReceived": "Responses Received",
    "dashboard.interviewRate": "Interview Rate",
    "dashboard.fromLastWeek": "from last week",
    "dashboard.newResponses": "new responses",
    "dashboard.replyRate": "reply rate",
    "dashboard.startJourney": "Start Your Journey",
    "dashboard.startJourneyDesc": "You're all set! Explore job opportunities tailored to your profile and accelerate your search.",
    "dashboard.exploreOpportunities": "Explore Opportunities",
    "dashboard.viewProfile": "View Profile",
    "dashboard.nextStep": "Next Step",
    "dashboard.browseMatches": "Browse 10+ personalized matches",
    "dashboard.timeToMatch": "Time to first match",
    "dashboard.minutes": "~2 minutes",
    "dashboard.tutorial1Title": "Tutorial #1: How to use the app",
    "dashboard.tutorial1Meta": "3 min \u00B7 Beginner",
    "dashboard.tutorial2Title": "Tutorial #2: Set up your profile for better matches",
    "dashboard.tutorial2Meta": "5 min \u00B7 Quick win",
    "dashboard.watch": "Watch",
    "dashboard.topMatches": "Top matches",
    "dashboard.bestFits": "Best fits for you",
    "dashboard.productAnalystIntern": "Product Analyst Intern",
    "dashboard.dataAnalyst": "Data Analyst",

    // Profile
    "profile.title": "Profile",
    "profile.yourBestAssets": "Your Best Assets",
    "profile.standOut": "What makes you stand out to employers",
    "profile.viewDetails": "View profile details",
    "profile.viewDetailsDesc": "This information is used to build your profile and generate your CV.",
    "profile.careerTargets": "Career Targets",
    "profile.primary": "PRIMARY",
    "profile.bestMatch": "Best match for your profile",
    "profile.searchJobs": "Search jobs",
    "profile.biAnalyst": "BI Analyst",
    "profile.growingDemand": "Growing demand, strong fit",
    "profile.includeInSearch": "Include in search",
    "profile.dataAnalyst": "Data Analyst",
    "profile.skillGap": "Skill gap: Advanced experimentation",
    "profile.learnSkill": "Learn skill",
    "profile.addToSearch": "Add to search",
    "profile.cvGenerator": "CV Generator",
    "profile.cvSubtitle": "Your baseline, system-generated CV",
    "profile.cvDesc": "This is a professional CV generated from your profile. It's not tailored to specific jobs \u2014 per-job optimization happens during the application process.",
    "profile.downloadCv": "Download CV",
    "profile.topSkill": "Top skill",
    "profile.highDemand": "High demand",
    "profile.differentiator": "Differentiator",
    "profile.foundation": "Foundation",
    "profile.focus": "Focus",
    "profile.productAnalytics": "Product Analytics",
    "profile.productAnalyticsDetail": "SQL, A/B testing, metrics design",
    "profile.crossFunctional": "Cross-functional Communication",
    "profile.crossFunctionalDetail": "Stakeholder alignment & storytelling with data",
    "profile.remoteFirst": "Remote-first Experience",
    "profile.remoteFirstDetail": "Proven async collaboration & self-management",
    "profile.yearsExperience": "years of experience",
    "profile.primaryExpertise": "Your primary expertise",
    "profile.flexibleForInternships": "Flexible for internships & entry roles",
    "profile.provenRemote": "Proven ability to deliver remotely",
    "profile.workPreference": "work preference",
    "profile.academicBackground": "Academic background",
    "profile.careerDirection": "Career direction",

    // Settings
    "settings.preferences": "Preferences",
    "settings.preferencesDesc": "Manage your account preferences and display settings.",
    "settings.connections": "Connections",
    "settings.connectionsDesc": "Manage your linked accounts and integrations.",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Choose how and when you want to be notified.",
    "settings.privacy": "Privacy & Security",
    "settings.privacyDesc": "Control your visibility and manage your data.",
    "settings.backToApp": "Back to app",
    "settings.accountSection": "Account",
    "settings.jobSearchSection": "Job Search",
    "settings.general": "General",
    "settings.jobAlerts": "Job Alerts",
    "settings.jobAlertsDesc": "Get notified when new jobs match your profile.",
    "settings.autoApply": "Auto-Apply",
    "settings.autoApplyDesc": "Automatically apply to high-match jobs on your behalf.",
    "settings.language": "Language",
    "settings.languageDesc": "Choose your preferred display language.",
    "settings.profileSection": "Profile",
    "settings.fullName": "Full Name",
    "settings.emailAddress": "Email Address",
    "settings.targetRole": "Target Role",
    "settings.notSet": "Not set",
    "settings.edit": "Edit",
    "settings.connect": "Connect",
    "settings.connected": "Connected",
    "settings.disconnect": "Disconnect",
    "settings.channels": "Channels",
    "settings.emailNotifications": "Email Notifications",
    "settings.emailNotificationsDesc": "Receive updates about new matches and responses.",
    "settings.pushNotifications": "Push Notifications",
    "settings.pushNotificationsDesc": "Get real-time browser alerts for urgent updates.",
    "settings.weeklyDigest": "Weekly Digest",
    "settings.weeklyDigestDesc": "A summary of your job search activity every Monday.",
    "settings.activity": "Activity",
    "settings.showActivityStatus": "Show Activity Status",
    "settings.showActivityStatusDesc": "Let employers see that you are actively searching.",
    "settings.visibility": "Visibility",
    "settings.profileVisible": "Profile Visible to Recruiters",
    "settings.profileVisibleDesc": "Allow recruiters to discover and view your profile.",
    "settings.data": "Data",
    "settings.exportData": "Export Data",
    "settings.exportDataDesc": "Download a copy of all your data.",
    "settings.export": "Export",
    "settings.clearHistory": "Clear Search History",
    "settings.clearHistoryDesc": "Remove all saved searches and recent activity.",
    "settings.clear": "Clear",
    "settings.dangerZone": "Danger Zone",
    "settings.deleteAccount": "Delete Account",
    "settings.deleteAccountDesc": "Permanently remove your account and all data.",
    "settings.delete": "Delete",
    "settings.signOut": "Sign Out",
    "settings.signOutDesc": "Log out of your account on this device.",
    "settings.linkedin": "LinkedIn",
    "settings.linkedinDesc": "Import profile data and track applications",
    "settings.gmail": "Gmail",
    "settings.gmailDesc": "Track responses and send applications",
    "settings.outlook": "Outlook",
    "settings.outlookDesc": "Email tracking and calendar scheduling",
    "settings.indeed": "Indeed",
    "settings.indeedDesc": "Sync job listings and application status",

    // Account
    "account.activity": "Activity",
    "account.last20weeks": "Last 20 weeks",
    "account.overview": "Overview",
    "account.applicationsSent": "Applications Sent",
    "account.interviews": "Interviews",
    "account.responses": "Responses",
    "account.connectedAccounts": "Connected Accounts",
    "account.manage": "Manage",
    "account.editProfile": "Edit Profile",
    "account.accountSettings": "Account Settings",
    "account.joined": "Joined",
    "account.less": "Less",
    "account.more": "More",
    "account.notConnected": "Not connected",
    "account.connectedStatus": "Connected",
    "account.notConnectedStatus": "Not connected",

    // Connect Accounts
    "connect.title": "Connect Your Accounts",
    "connect.backToOnboarding": "Back to onboarding",
    "connect.skipForNow": "Skip for now",
    "connect.continue": "Continue",

    // Opportunities List
    "opp.title": "Opportunities",
    "opp.highConfidenceMatches": "{count} high-confidence matches for you",
    "opp.searchPlaceholder": "Search roles or companies...",
    "opp.filters": "Filters",
    "opp.loadMore": "Load more",
    "opp.applyNow": "Apply now",
    "opp.strongFit": "Strong fit",
    "opp.goodFit": "Good fit",
    "opp.stretch": "Stretch",
    "opp.noOpportunitiesTitle": "No high-confidence opportunities right now",
    "opp.noOpportunitiesDesc": "Based on your profile and recent activity, applying right now would likely have low returns.",
    "opp.improveChances": "Improve my chances",

    // Opportunity data
    "opp.data.3daysAgo": "3 days ago",
    "opp.data.5daysAgo": "5 days ago",
    "opp.data.1weekAgo": "1 week ago",
    "opp.data.4daysAgo": "4 days ago",
    "opp.data.2daysAgo": "2 days ago",
    "opp.data.1dayAgo": "1 day ago",
    "opp.data.6daysAgo": "6 days ago",
    "opp.data.lowApplicant": "Low applicant volume",
    "opp.data.internFriendly": "Intern-friendly",
    "opp.data.respondsQuickly": "Responds quickly",
    "opp.data.growingTeam": "Growing team",
    "opp.data.startupEnv": "Startup environment",
    "opp.data.competitive": "Competitive",
    "opp.data.explanation1": "Your profile closely matches the role's requirements, and similar candidates received interviews here within 2 weeks.",
    "opp.data.explanation2": "Your SQL and Python skills match 90% of the requirements. This company has hired from your university before.",
    "opp.data.explanation3": "Your analytics background is relevant, and the team is actively expanding. Previous applicants with similar profiles advanced to interviews.",
    "opp.data.explanation4": "Your project experience aligns with their product focus. They value analytical backgrounds for this role.",
    "opp.data.explanation5": "This role typically requires more experience, but your quantitative skills could bridge the gap. Worth trying if you have capacity.",

    // Actions list data
    "actions.data.followUpTechStart": "Follow up with TechStart Inc",
    "actions.data.10daysSince": "10 days since application",
    "actions.data.followUpDataFlow": "Follow up with DataFlow",
    "actions.data.7daysSince": "7 days since application",
    "actions.data.updateResume": "Update resume for Product roles",
    "actions.data.increasesMatch": "Increases match rate by ~15%",
    "actions.data.addPortfolio": "Add portfolio link to LinkedIn",
    "actions.data.boostsVisibility": "Boosts profile visibility",
    "actions.data.followUpEmail": "Follow up email",
    "actions.data.prepareInterview": "Prepare interview",
    "actions.data.codingChallenge": "Coding challenge",
    "actions.data.scheduleCall": "Schedule call",
    "actions.data.reviewRequirements": "Review requirements",
    "actions.data.submitPortfolio": "Submit portfolio",
    "actions.data.portfolioReview": "Portfolio review",
    "actions.data.designTest": "Design test",
    "actions.data.phoneScreen": "Phone screen",
    "actions.data.technicalInterview": "Technical interview",
    "actions.data.caseStudy": "Case study",
    "actions.data.finalRound": "Final round",

    // Action detail data - stages
    "actionDetail.data.applicationSubmitted": "Application Submitted",
    "actionDetail.data.applicationReview": "Application Review",
    "actionDetail.data.interview": "Interview",
    "actionDetail.data.decision": "Decision",
    "actionDetail.data.technicalAssessment": "Technical Assessment",
    "actionDetail.data.finalInterview": "Final Interview",
    "actionDetail.data.screeningCall": "Screening Call",
    "actionDetail.data.finalRound": "Final Round",

    // Action detail data - tasks
    "actionDetail.data.sendFollowUp": "Send follow-up email",
    "actionDetail.data.sendFollowUpImpact": "Increases response rate by 25%",
    "actionDetail.data.prepareQuestions": "Prepare 2-3 interview questions",
    "actionDetail.data.prepareQuestionsImpact": "Candidates who prepare increase success rate by ~30%",
    "actionDetail.data.researchCompany": "Research company background",
    "actionDetail.data.researchCompanyImpact": "Shows genuine interest to recruiters",
    "actionDetail.data.tailorCV": "Tailor CV for this role",
    "actionDetail.data.tailorCVImpact": "+6% impact on Application Health",
    "actionDetail.data.prepareTellMe": "Prepare 'Tell me about yourself' answer",
    "actionDetail.data.prepareTellMeImpact": "First impression matters most",
    "actionDetail.data.completeCoding": "Complete coding challenge",
    "actionDetail.data.completeCodingImpact": "Critical for advancement",
    "actionDetail.data.scheduleTechnical": "Schedule technical call",
    "actionDetail.data.scheduleTechnicalImpact": "Shows promptness and interest",
    "actionDetail.data.reviewJobReq": "Review job requirements",
    "actionDetail.data.reviewJobReqImpact": "Foundation for all prep",
    "actionDetail.data.submitPortfolio": "Submit portfolio",
    "actionDetail.data.submitPortfolioImpact": "Differentiates you from 80% of candidates",

    // Action detail data - next actions
    "actionDetail.data.sendFollowUp2days": "Send follow-up email in 2 days",
    "actionDetail.data.completeCodingChallenge": "Complete coding challenge",
    "actionDetail.data.submitPortfolioLink": "Submit portfolio link",

    // Action detail data - recruiter signals
    "actionDetail.data.reviewTime1": "5\u20137 days average",
    "actionDetail.data.profileView1": "Likely within 48 hours",
    "actionDetail.data.reviewTime2": "2\u20133 days for assessments",
    "actionDetail.data.profileView2": "Already confirmed",
    "actionDetail.data.reviewTime3": "4\u20135 days for screening",
    "actionDetail.data.profileView3": "Likely today",
    "actionDetail.data.low": "Low",
    "actionDetail.data.veryLow": "Very Low",

    // Opportunity Detail
    "oppDetail.back": "Back",
    "oppDetail.aheadOfApplicants": "You're ahead of most applicants",
    "oppDetail.aheadReason": "Based on skills match, experience level, and current competition",
    "oppDetail.lowGhosting": "Low chance of being ghosted",
    "oppDetail.low": "Low",
    "oppDetail.shortProcess": "Short process",
    "oppDetail.interviews": "2 interviews",
    "oppDetail.fastDecision": "Fast decision",
    "oppDetail.weeks": "\u22482\u20133 weeks",
    "oppDetail.whyStrongMatch": "WHY IT'S A SUPER STRONG MATCH:",
    "oppDetail.matchDesc1": "Your profile aligns well with this role, both in terms of skills and experience. The hiring process is short, competition remains limited, and the team is actively moving candidates forward.",
    "oppDetail.matchDesc2": "You are already competitive for this position, and applying now is a low-risk, high-potential step in your job search.",
    "oppDetail.optionalSkills": "OPTIONAL SKILLS TO STRENGTHEN YOUR APPLICATION:",
    "oppDetail.youMatch": "YOU MATCH",
    "oppDetail.ofRequirements": "92% of requirements",
    "oppDetail.noNeed": "You do not need these to apply. They improve interview confidence.",
    "oppDetail.skillsToDevelop": "Skills to Develop (Optional):",
    "oppDetail.advancedSQL": "Advanced SQL",
    "oppDetail.advancedSQLDesc": "Experience with complex query optimization and database performance tuning",
    "oppDetail.tableauPowerBI": "Tableau/Power BI",
    "oppDetail.tableauPowerBIDesc": "Building interactive dashboards and real-time visualizations for stakeholders",
    "oppDetail.quickWins": "Quick wins to strengthen your application:",
    "oppDetail.quickWin1": "Advanced SQL course \u2022 Can be done in under 7 days",
    "oppDetail.quickWin2": "Build a practice dashboard \u2022 Show it in interviews",
    "oppDetail.whoDesignedFor": "WHO THIS ROLE IS DESIGNED FOR:",
    "oppDetail.whoDesc1": "This role is well suited if you are early in your career or transitioning into an analytical role, and you already have hands-on experience through studies, projects, or previous work.",
    "oppDetail.whoDesc2": "What matters most here is your ability to work with data and explain your reasoning \u2014 not having a long list of past job titles.",
    "oppDetail.whatToExpect": "WHAT TO EXPECT FROM THE ROLE:",
    "oppDetail.expectDesc1": "This is a full-time, permanent position with a clearly defined compensation structure and a standard interview process.",
    "oppDetail.expectDesc2": "You can expect clear expectations, structured onboarding, and a stable working environment.",
    "oppDetail.aboutCompany": "ABOUT THE COMPANY ENVIRONMENT:",
    "oppDetail.companyDesc1": "You would be joining a large, established organization with well-defined teams and processes.",
    "oppDetail.companyDesc2": "This type of environment tends to offer stability, learning opportunities, and recognizable experience that strengthens your profile over time.",
    "oppDetail.preInterview": "PRE-INTERVIEW CHECKLIST:",
    "oppDetail.coverLetter": "Tailored cover letter with metrics",
    "oppDetail.starStories": "2\u20133 STAR stories prepared",
    "oppDetail.smartQuestions": "2 smart questions about the company",
    "oppDetail.dataExamples": "3 data-driven examples rehearsed",
    "oppDetail.applyWellPositioned": "Apply now \u2014 you're well positioned",
    "oppDetail.jobInfo": "JOB INFORMATION:",
    "oppDetail.openOriginal": "Open original post",
    "oppDetail.paidInternship": "paid internship",
    "oppDetail.daysAgo": "3 days ago",

    // Apply Page
    "apply.back": "Back",
    "apply.submittedTitle": "Application Submitted!",
    "apply.submittedDesc": "Your application has been sent. We'll notify you when the recruiter reviews it.",
    "apply.viewDetails": "View Application Details",
    "apply.draftSaved": "Draft Saved",
    "apply.draftDesc": "Your application draft has been saved. You can resume anytime.",
    "apply.resumeApp": "Resume Application",
    "apply.company": "Company",
    "apply.location": "Location",
    "apply.salary": "Salary",
    "apply.match": "Match",
    "apply.yourMessage": "Your Application Message",
    "apply.messageTip": "Tip: This message has been optimized for your profile and target role.",
    "apply.cvSubmitted": "CV Being Submitted",
    "apply.cvGenerated": "Generated \u2022 Optimized for this role",
    "apply.saveForLater": "Save for Later",
    "apply.applyAndSend": "Apply & Send",

    // Actions List
    "actions.title": "Application",
    "actions.searchPlaceholder": "Search by job title...",
    "actions.filterUrgency": "Filter by urgency",
    "actions.veryUrgent": "Very urgent",
    "actions.urgent": "Urgent",
    "actions.normal": "Normal",
    "actions.filterDate": "Filter by date",
    "actions.last1Day": "Last 1 day",
    "actions.last3Days": "Last 3 days",
    "actions.last7Days": "Last 7 days",
    "actions.allTime": "All time",
    "actions.applied": "Applied",
    "actions.tasks": "Tasks:",
    "actions.loadMore": "Load more",

    // Action Detail
    "actionDetail.backToApps": "Back to Applications",
    "actionDetail.currentStage": "Current Stage",
    "actionDetail.appProgress": "Application Progress",
    "actionDetail.reassurance": "You're doing great. Things are moving forward \u2014 stay focused on what's next.",
    "actionDetail.whatToExpect": "What to expect:",
    "actionDetail.typicalReview": "Typical review time",
    "actionDetail.ghostingRisk": "Ghosting risk",
    "actionDetail.timeline": "Application Timeline",
    "actionDetail.inProgress": "In progress",
    "actionDetail.your": "Your ",
    "actionDetail.stepsForward": "Steps to Move Forward :",
    "actionDetail.estimatedSalary": "Estimated Salary:",
    "actionDetail.sendFollowUp": "Send a follow-up",

    // Send Follow-up
    "followUp.backToApp": "Back to Application",
    "followUp.title": "Send a follow-up",
    "followUp.role": "Role",
    "followUp.company": "Company",
    "followUp.stage": "Stage",
    "followUp.appliedOn": "Applied on",
    "followUp.suggestedMessage": "Suggested follow-up message",
    "followUp.messageDesc": "Polite, concise, and optimized for your current application stage",
    "followUp.recommendedTiming": "Recommended timing",
    "followUp.timingValue": "5\u20137 days after application",
    "followUp.note1": "Sending a follow-up increases response likelihood",
    "followUp.note2": "One follow-up per application stage",
    "followUp.cancel": "Cancel",
    "followUp.editMessage": "Edit message",
    "followUp.send": "Send follow-up",
    "followUp.sentTitle": "Follow-up sent successfully",
    "followUp.sentDesc": "Your follow-up message has been sent. You'll be notified if there's a response.",
    "followUp.backToDetails": "Back to Application Details",
    "followUp.cancelledTitle": "Follow-up cancelled",
    "followUp.cancelledDesc": "You can send a follow-up later when you're ready.",
  },
  fr: {
    // TopNav tabs
    "nav.dashboard": "Tableau de bord",
    "nav.opportunities": "Opportunit\u00E9s",
    "nav.application": "Candidature",
    "nav.profile": "Profil",
    "nav.account": "Compte",
    "nav.settings": "Param\u00E8tres",
    "nav.language": "Langue",
    "nav.signOut": "D\u00E9connexion",

    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.matchesFound": "Correspondances",
    "dashboard.outreachSent": "Messages envoy\u00E9s",
    "dashboard.responsesReceived": "R\u00E9ponses re\u00E7ues",
    "dashboard.interviewRate": "Taux d\u2019entretien",
    "dashboard.fromLastWeek": "par rapport \u00E0 la semaine derni\u00E8re",
    "dashboard.newResponses": "nouvelles r\u00E9ponses",
    "dashboard.replyRate": "taux de r\u00E9ponse",
    "dashboard.startJourney": "Commencez votre parcours",
    "dashboard.startJourneyDesc": "Vous \u00EAtes pr\u00EAt ! D\u00E9couvrez des offres d\u2019emploi adapt\u00E9es \u00E0 votre profil et acc\u00E9l\u00E9rez votre recherche.",
    "dashboard.exploreOpportunities": "Explorer les opportunit\u00E9s",
    "dashboard.viewProfile": "Voir le profil",
    "dashboard.nextStep": "\u00C9tape suivante",
    "dashboard.browseMatches": "Parcourir 10+ correspondances personnalis\u00E9es",
    "dashboard.timeToMatch": "Temps avant le premier match",
    "dashboard.minutes": "~2 minutes",
    "dashboard.tutorial1Title": "Tutoriel #1 : Comment utiliser l\u2019application",
    "dashboard.tutorial1Meta": "3 min \u00B7 D\u00E9butant",
    "dashboard.tutorial2Title": "Tutoriel #2 : Optimisez votre profil pour de meilleures correspondances",
    "dashboard.tutorial2Meta": "5 min \u00B7 Rapide",
    "dashboard.watch": "Regarder",
    "dashboard.topMatches": "Meilleures correspondances",
    "dashboard.bestFits": "Les plus adapt\u00E9es pour vous",
    "dashboard.productAnalystIntern": "Analyste Produit Stagiaire",
    "dashboard.dataAnalyst": "Analyste de donn\u00E9es",

    // Profile
    "profile.title": "Profil",
    "profile.yourBestAssets": "Vos meilleurs atouts",
    "profile.standOut": "Ce qui vous distingue aupr\u00E8s des employeurs",
    "profile.viewDetails": "Voir les d\u00E9tails du profil",
    "profile.viewDetailsDesc": "Ces informations sont utilis\u00E9es pour construire votre profil et g\u00E9n\u00E9rer votre CV.",
    "profile.careerTargets": "Objectifs de carri\u00E8re",
    "profile.primary": "PRINCIPAL",
    "profile.bestMatch": "Meilleure correspondance pour votre profil",
    "profile.searchJobs": "Rechercher des emplois",
    "profile.biAnalyst": "Analyste BI",
    "profile.growingDemand": "Demande croissante, bonne ad\u00E9quation",
    "profile.includeInSearch": "Inclure dans la recherche",
    "profile.dataAnalyst": "Analyste de donn\u00E9es",
    "profile.skillGap": "Lacune : Exp\u00E9rimentation avanc\u00E9e",
    "profile.learnSkill": "Apprendre la comp\u00E9tence",
    "profile.addToSearch": "Ajouter \u00E0 la recherche",
    "profile.cvGenerator": "G\u00E9n\u00E9rateur de CV",
    "profile.cvSubtitle": "Votre CV de r\u00E9f\u00E9rence, g\u00E9n\u00E9r\u00E9 automatiquement",
    "profile.cvDesc": "Il s\u2019agit d\u2019un CV professionnel g\u00E9n\u00E9r\u00E9 \u00E0 partir de votre profil. Il n\u2019est pas adapt\u00E9 \u00E0 des postes sp\u00E9cifiques \u2014 l\u2019optimisation se fait lors du processus de candidature.",
    "profile.downloadCv": "T\u00E9l\u00E9charger le CV",
    "profile.topSkill": "Comp\u00E9tence cl\u00E9",
    "profile.highDemand": "Forte demande",
    "profile.differentiator": "Diff\u00E9renciateur",
    "profile.foundation": "Fondation",
    "profile.focus": "Orientation",
    "profile.productAnalytics": "Analytique Produit",
    "profile.productAnalyticsDetail": "SQL, tests A/B, conception de m\u00E9triques",
    "profile.crossFunctional": "Communication transversale",
    "profile.crossFunctionalDetail": "Alignement des parties prenantes et storytelling",
    "profile.remoteFirst": "Exp\u00E9rience en t\u00E9l\u00E9travail",
    "profile.remoteFirstDetail": "Collaboration asynchrone et autonomie",
    "profile.yearsExperience": "ann\u00E9es d\u2019exp\u00E9rience",
    "profile.primaryExpertise": "Votre expertise principale",
    "profile.flexibleForInternships": "Flexible pour stages et postes juniors",
    "profile.provenRemote": "Capacit\u00E9 prouv\u00E9e en t\u00E9l\u00E9travail",
    "profile.workPreference": "pr\u00E9f\u00E9rence de travail",
    "profile.academicBackground": "Formation acad\u00E9mique",
    "profile.careerDirection": "Direction de carri\u00E8re",

    // Settings
    "settings.preferences": "Pr\u00E9f\u00E9rences",
    "settings.preferencesDesc": "G\u00E9rez vos pr\u00E9f\u00E9rences de compte et d\u2019affichage.",
    "settings.connections": "Connexions",
    "settings.connectionsDesc": "G\u00E9rez vos comptes li\u00E9s et int\u00E9grations.",
    "settings.notifications": "Notifications",
    "settings.notificationsDesc": "Choisissez comment et quand vous souhaitez \u00EAtre notifi\u00E9.",
    "settings.privacy": "Confidentialit\u00E9 et s\u00E9curit\u00E9",
    "settings.privacyDesc": "Contr\u00F4lez votre visibilit\u00E9 et g\u00E9rez vos donn\u00E9es.",
    "settings.backToApp": "Retour \u00E0 l\u2019application",
    "settings.accountSection": "Compte",
    "settings.jobSearchSection": "Recherche d\u2019emploi",
    "settings.general": "G\u00E9n\u00E9ral",
    "settings.jobAlerts": "Alertes emploi",
    "settings.jobAlertsDesc": "Soyez notifi\u00E9 quand de nouveaux emplois correspondent \u00E0 votre profil.",
    "settings.autoApply": "Candidature automatique",
    "settings.autoApplyDesc": "Postulez automatiquement aux emplois \u00E0 forte correspondance.",
    "settings.language": "Langue",
    "settings.languageDesc": "Choisissez votre langue d\u2019affichage pr\u00E9f\u00E9r\u00E9e.",
    "settings.profileSection": "Profil",
    "settings.fullName": "Nom complet",
    "settings.emailAddress": "Adresse e-mail",
    "settings.targetRole": "Poste recherch\u00E9",
    "settings.notSet": "Non d\u00E9fini",
    "settings.edit": "Modifier",
    "settings.connect": "Connecter",
    "settings.connected": "Connect\u00E9",
    "settings.disconnect": "D\u00E9connecter",
    "settings.channels": "Canaux",
    "settings.emailNotifications": "Notifications par e-mail",
    "settings.emailNotificationsDesc": "Recevez des mises \u00E0 jour sur les nouvelles correspondances et r\u00E9ponses.",
    "settings.pushNotifications": "Notifications push",
    "settings.pushNotificationsDesc": "Recevez des alertes en temps r\u00E9el pour les mises \u00E0 jour urgentes.",
    "settings.weeklyDigest": "R\u00E9sum\u00E9 hebdomadaire",
    "settings.weeklyDigestDesc": "Un r\u00E9sum\u00E9 de votre activit\u00E9 de recherche chaque lundi.",
    "settings.activity": "Activit\u00E9",
    "settings.showActivityStatus": "Afficher le statut d\u2019activit\u00E9",
    "settings.showActivityStatusDesc": "Permettez aux employeurs de voir que vous recherchez activement.",
    "settings.visibility": "Visibilit\u00E9",
    "settings.profileVisible": "Profil visible par les recruteurs",
    "settings.profileVisibleDesc": "Autorisez les recruteurs \u00E0 d\u00E9couvrir et consulter votre profil.",
    "settings.data": "Donn\u00E9es",
    "settings.exportData": "Exporter les donn\u00E9es",
    "settings.exportDataDesc": "T\u00E9l\u00E9chargez une copie de toutes vos donn\u00E9es.",
    "settings.export": "Exporter",
    "settings.clearHistory": "Effacer l\u2019historique de recherche",
    "settings.clearHistoryDesc": "Supprimez toutes les recherches enregistr\u00E9es et l\u2019activit\u00E9 r\u00E9cente.",
    "settings.clear": "Effacer",
    "settings.dangerZone": "Zone de danger",
    "settings.deleteAccount": "Supprimer le compte",
    "settings.deleteAccountDesc": "Supprimez d\u00E9finitivement votre compte et toutes vos donn\u00E9es.",
    "settings.delete": "Supprimer",
    "settings.signOut": "D\u00E9connexion",
    "settings.signOutDesc": "D\u00E9connectez-vous de votre compte sur cet appareil.",
    "settings.linkedin": "LinkedIn",
    "settings.linkedinDesc": "Importez les donn\u00E9es de profil et suivez les candidatures",
    "settings.gmail": "Gmail",
    "settings.gmailDesc": "Suivez les r\u00E9ponses et envoyez des candidatures",
    "settings.outlook": "Outlook",
    "settings.outlookDesc": "Suivi des e-mails et planification du calendrier",
    "settings.indeed": "Indeed",
    "settings.indeedDesc": "Synchronisez les offres et le statut des candidatures",

    // Account
    "account.activity": "Activit\u00E9",
    "account.last20weeks": "20 derni\u00E8res semaines",
    "account.overview": "Aper\u00E7u",
    "account.applicationsSent": "Candidatures envoy\u00E9es",
    "account.interviews": "Entretiens",
    "account.responses": "R\u00E9ponses",
    "account.connectedAccounts": "Comptes connect\u00E9s",
    "account.manage": "G\u00E9rer",
    "account.editProfile": "Modifier le profil",
    "account.accountSettings": "Param\u00E8tres du compte",
    "account.joined": "Inscrit",
    "account.less": "Moins",
    "account.more": "Plus",
    "account.notConnected": "Non connect\u00E9",
    "account.connectedStatus": "Connect\u00E9",
    "account.notConnectedStatus": "Non connect\u00E9",

    // Connect Accounts
    "connect.title": "Connectez vos comptes",
    "connect.backToOnboarding": "Retour \u00E0 l\u2019int\u00E9gration",
    "connect.skipForNow": "Passer pour l\u2019instant",
    "connect.continue": "Continuer",

    // Opportunities List
    "opp.title": "Opportunit\u00E9s",
    "opp.highConfidenceMatches": "{count} correspondances \u00E0 forte probabilit\u00E9 pour vous",
    "opp.searchPlaceholder": "Rechercher des postes ou entreprises...",
    "opp.filters": "Filtres",
    "opp.loadMore": "Voir plus",
    "opp.applyNow": "Postuler",
    "opp.strongFit": "Forte ad\u00E9quation",
    "opp.goodFit": "Bonne ad\u00E9quation",
    "opp.stretch": "Ambitieux",
    "opp.noOpportunitiesTitle": "Pas d\u2019opportunit\u00E9s \u00E0 forte probabilit\u00E9 pour le moment",
    "opp.noOpportunitiesDesc": "D\u2019apr\u00E8s votre profil et votre activit\u00E9 r\u00E9cente, postuler maintenant aurait probablement peu de retour.",
    "opp.improveChances": "Am\u00E9liorer mes chances",

    // Opportunity data
    "opp.data.3daysAgo": "Il y a 3 jours",
    "opp.data.5daysAgo": "Il y a 5 jours",
    "opp.data.1weekAgo": "Il y a 1 semaine",
    "opp.data.4daysAgo": "Il y a 4 jours",
    "opp.data.2daysAgo": "Il y a 2 jours",
    "opp.data.1dayAgo": "Il y a 1 jour",
    "opp.data.6daysAgo": "Il y a 6 jours",
    "opp.data.lowApplicant": "Peu de candidats",
    "opp.data.internFriendly": "Adapt\u00E9 aux stagiaires",
    "opp.data.respondsQuickly": "R\u00E9pond rapidement",
    "opp.data.growingTeam": "\u00C9quipe en croissance",
    "opp.data.startupEnv": "Environnement startup",
    "opp.data.competitive": "Comp\u00E9titif",
    "opp.data.explanation1": "Votre profil correspond \u00E9troitement aux exigences du poste, et des candidats similaires ont obtenu des entretiens ici en 2 semaines.",
    "opp.data.explanation2": "Vos comp\u00E9tences en SQL et Python correspondent \u00E0 90% des exigences. Cette entreprise a d\u00E9j\u00E0 recrut\u00E9 dans votre universit\u00E9.",
    "opp.data.explanation3": "Votre exp\u00E9rience en analyse est pertinente et l\u2019\u00E9quipe est en pleine expansion. Des candidats au profil similaire ont avanc\u00E9 aux entretiens.",
    "opp.data.explanation4": "Votre exp\u00E9rience projet correspond \u00E0 leur focus produit. Ils appr\u00E9cient les profils analytiques pour ce poste.",
    "opp.data.explanation5": "Ce poste requiert g\u00E9n\u00E9ralement plus d\u2019exp\u00E9rience, mais vos comp\u00E9tences quantitatives peuvent combler l\u2019\u00E9cart. \u00C0 tenter si vous avez la capacit\u00E9.",

    // Actions list data
    "actions.data.followUpTechStart": "Relancer TechStart Inc",
    "actions.data.10daysSince": "10 jours depuis la candidature",
    "actions.data.followUpDataFlow": "Relancer DataFlow",
    "actions.data.7daysSince": "7 jours depuis la candidature",
    "actions.data.updateResume": "Mettre \u00E0 jour le CV pour les postes Produit",
    "actions.data.increasesMatch": "Augmente le taux de correspondance de ~15%",
    "actions.data.addPortfolio": "Ajouter un lien portfolio sur LinkedIn",
    "actions.data.boostsVisibility": "Am\u00E9liore la visibilit\u00E9 du profil",
    "actions.data.followUpEmail": "E-mail de relance",
    "actions.data.prepareInterview": "Pr\u00E9parer l\u2019entretien",
    "actions.data.codingChallenge": "D\u00E9fi de code",
    "actions.data.scheduleCall": "Planifier un appel",
    "actions.data.reviewRequirements": "Revoir les exigences",
    "actions.data.submitPortfolio": "Soumettre le portfolio",
    "actions.data.portfolioReview": "Revue de portfolio",
    "actions.data.designTest": "Test de design",
    "actions.data.phoneScreen": "Entretien t\u00E9l\u00E9phonique",
    "actions.data.technicalInterview": "Entretien technique",
    "actions.data.caseStudy": "\u00C9tude de cas",
    "actions.data.finalRound": "Dernier tour",

    // Action detail data - stages
    "actionDetail.data.applicationSubmitted": "Candidature envoy\u00E9e",
    "actionDetail.data.applicationReview": "Examen de la candidature",
    "actionDetail.data.interview": "Entretien",
    "actionDetail.data.decision": "D\u00E9cision",
    "actionDetail.data.technicalAssessment": "\u00C9valuation technique",
    "actionDetail.data.finalInterview": "Entretien final",
    "actionDetail.data.screeningCall": "Appel de pr\u00E9s\u00E9lection",
    "actionDetail.data.finalRound": "Dernier tour",

    // Action detail data - tasks
    "actionDetail.data.sendFollowUp": "Envoyer un e-mail de relance",
    "actionDetail.data.sendFollowUpImpact": "Augmente le taux de r\u00E9ponse de 25%",
    "actionDetail.data.prepareQuestions": "Pr\u00E9parer 2-3 questions d\u2019entretien",
    "actionDetail.data.prepareQuestionsImpact": "Les candidats pr\u00E9par\u00E9s augmentent leur taux de succ\u00E8s de ~30%",
    "actionDetail.data.researchCompany": "Rechercher l\u2019entreprise",
    "actionDetail.data.researchCompanyImpact": "Montre un int\u00E9r\u00EAt sinc\u00E8re aux recruteurs",
    "actionDetail.data.tailorCV": "Adapter le CV pour ce poste",
    "actionDetail.data.tailorCVImpact": "+6% d\u2019impact sur la sant\u00E9 de la candidature",
    "actionDetail.data.prepareTellMe": "Pr\u00E9parer la r\u00E9ponse \u00AB Parlez-moi de vous \u00BB",
    "actionDetail.data.prepareTellMeImpact": "La premi\u00E8re impression compte le plus",
    "actionDetail.data.completeCoding": "Compl\u00E9ter le d\u00E9fi de code",
    "actionDetail.data.completeCodingImpact": "Essentiel pour avancer",
    "actionDetail.data.scheduleTechnical": "Planifier l\u2019appel technique",
    "actionDetail.data.scheduleTechnicalImpact": "Montre votre r\u00E9activit\u00E9 et int\u00E9r\u00EAt",
    "actionDetail.data.reviewJobReq": "Revoir les exigences du poste",
    "actionDetail.data.reviewJobReqImpact": "Base de toute pr\u00E9paration",
    "actionDetail.data.submitPortfolio": "Soumettre le portfolio",
    "actionDetail.data.submitPortfolioImpact": "Vous diff\u00E9rencie de 80% des candidats",

    // Action detail data - next actions
    "actionDetail.data.sendFollowUp2days": "Envoyer un e-mail de relance dans 2 jours",
    "actionDetail.data.completeCodingChallenge": "Compl\u00E9ter le d\u00E9fi de code",
    "actionDetail.data.submitPortfolioLink": "Soumettre le lien du portfolio",

    // Action detail data - recruiter signals
    "actionDetail.data.reviewTime1": "5\u20137 jours en moyenne",
    "actionDetail.data.profileView1": "Probable sous 48 heures",
    "actionDetail.data.reviewTime2": "2\u20133 jours pour les \u00E9valuations",
    "actionDetail.data.profileView2": "D\u00E9j\u00E0 confirm\u00E9",
    "actionDetail.data.reviewTime3": "4\u20135 jours pour la pr\u00E9s\u00E9lection",
    "actionDetail.data.profileView3": "Probable aujourd\u2019hui",
    "actionDetail.data.low": "Faible",
    "actionDetail.data.veryLow": "Tr\u00E8s faible",

    // Opportunity Detail
    "oppDetail.back": "Retour",
    "oppDetail.aheadOfApplicants": "Vous \u00EAtes en avance sur la plupart des candidats",
    "oppDetail.aheadReason": "Bas\u00E9 sur la correspondance des comp\u00E9tences, le niveau d\u2019exp\u00E9rience et la concurrence actuelle",
    "oppDetail.lowGhosting": "Faible risque de ghosting",
    "oppDetail.low": "Faible",
    "oppDetail.shortProcess": "Processus court",
    "oppDetail.interviews": "2 entretiens",
    "oppDetail.fastDecision": "D\u00E9cision rapide",
    "oppDetail.weeks": "\u22482\u20133 semaines",
    "oppDetail.whyStrongMatch": "POURQUOI C\u2019EST UNE EXCELLENTE CORRESPONDANCE :",
    "oppDetail.matchDesc1": "Votre profil correspond bien \u00E0 ce poste, tant en termes de comp\u00E9tences que d\u2019exp\u00E9rience. Le processus de recrutement est court, la concurrence reste limit\u00E9e et l\u2019\u00E9quipe fait avancer activement les candidats.",
    "oppDetail.matchDesc2": "Vous \u00EAtes d\u00E9j\u00E0 comp\u00E9titif pour ce poste, et postuler maintenant est une \u00E9tape \u00E0 faible risque et \u00E0 fort potentiel dans votre recherche d\u2019emploi.",
    "oppDetail.optionalSkills": "COMP\u00C9TENCES OPTIONNELLES POUR RENFORCER VOTRE CANDIDATURE :",
    "oppDetail.youMatch": "VOUS CORRESPONDEZ \u00C0",
    "oppDetail.ofRequirements": "92% des exigences",
    "oppDetail.noNeed": "Vous n\u2019en avez pas besoin pour postuler. Elles am\u00E9liorent votre confiance en entretien.",
    "oppDetail.skillsToDevelop": "Comp\u00E9tences \u00E0 d\u00E9velopper (optionnel) :",
    "oppDetail.advancedSQL": "SQL Avanc\u00E9",
    "oppDetail.advancedSQLDesc": "Exp\u00E9rience en optimisation de requ\u00EAtes complexes et performances de bases de donn\u00E9es",
    "oppDetail.tableauPowerBI": "Tableau/Power BI",
    "oppDetail.tableauPowerBIDesc": "Cr\u00E9ation de tableaux de bord interactifs et visualisations en temps r\u00E9el",
    "oppDetail.quickWins": "Actions rapides pour renforcer votre candidature :",
    "oppDetail.quickWin1": "Cours SQL avanc\u00E9 \u2022 R\u00E9alisable en moins de 7 jours",
    "oppDetail.quickWin2": "Cr\u00E9er un tableau de bord d\u2019entra\u00EEnement \u2022 Montrez-le en entretien",
    "oppDetail.whoDesignedFor": "\u00C0 QUI S\u2019ADRESSE CE POSTE :",
    "oppDetail.whoDesc1": "Ce poste convient si vous \u00EAtes en d\u00E9but de carri\u00E8re ou en transition vers un r\u00F4le analytique, et que vous avez d\u00E9j\u00E0 une exp\u00E9rience pratique \u00E0 travers vos \u00E9tudes, projets ou exp\u00E9riences professionnelles.",
    "oppDetail.whoDesc2": "Ce qui compte le plus ici, c\u2019est votre capacit\u00E9 \u00E0 travailler avec les donn\u00E9es et \u00E0 expliquer votre raisonnement \u2014 pas d\u2019avoir une longue liste de postes pass\u00E9s.",
    "oppDetail.whatToExpect": "CE QUE VOUS POUVEZ ATTENDRE DU POSTE :",
    "oppDetail.expectDesc1": "Il s\u2019agit d\u2019un poste \u00E0 temps plein et permanent avec une structure de r\u00E9mun\u00E9ration clairement d\u00E9finie et un processus d\u2019entretien standard.",
    "oppDetail.expectDesc2": "Vous pouvez vous attendre \u00E0 des attentes claires, un onboarding structur\u00E9 et un environnement de travail stable.",
    "oppDetail.aboutCompany": "\u00C0 PROPOS DE L\u2019ENVIRONNEMENT DE L\u2019ENTREPRISE :",
    "oppDetail.companyDesc1": "Vous rejoindriez une grande organisation \u00E9tablie avec des \u00E9quipes et des processus bien d\u00E9finis.",
    "oppDetail.companyDesc2": "Ce type d\u2019environnement tend \u00E0 offrir de la stabilit\u00E9, des opportunit\u00E9s d\u2019apprentissage et une exp\u00E9rience reconnue qui renforce votre profil au fil du temps.",
    "oppDetail.preInterview": "CHECKLIST PR\u00C9-ENTRETIEN :",
    "oppDetail.coverLetter": "Lettre de motivation personnalis\u00E9e avec des chiffres",
    "oppDetail.starStories": "2\u20133 histoires STAR pr\u00E9par\u00E9es",
    "oppDetail.smartQuestions": "2 questions pertinentes sur l\u2019entreprise",
    "oppDetail.dataExamples": "3 exemples bas\u00E9s sur les donn\u00E9es r\u00E9p\u00E9t\u00E9s",
    "oppDetail.applyWellPositioned": "Postuler \u2014 vous \u00EAtes bien positionn\u00E9",
    "oppDetail.jobInfo": "INFORMATIONS SUR LE POSTE :",
    "oppDetail.openOriginal": "Voir l\u2019annonce originale",
    "oppDetail.paidInternship": "stage r\u00E9mun\u00E9r\u00E9",
    "oppDetail.daysAgo": "il y a 3 jours",

    // Apply Page
    "apply.back": "Retour",
    "apply.submittedTitle": "Candidature envoy\u00E9e !",
    "apply.submittedDesc": "Votre candidature a \u00E9t\u00E9 envoy\u00E9e. Nous vous avertirons lorsque le recruteur l\u2019examinera.",
    "apply.viewDetails": "Voir les d\u00E9tails de la candidature",
    "apply.draftSaved": "Brouillon enregistr\u00E9",
    "apply.draftDesc": "Votre brouillon de candidature a \u00E9t\u00E9 enregistr\u00E9. Vous pouvez reprendre \u00E0 tout moment.",
    "apply.resumeApp": "Reprendre la candidature",
    "apply.company": "Entreprise",
    "apply.location": "Lieu",
    "apply.salary": "Salaire",
    "apply.match": "Correspondance",
    "apply.yourMessage": "Votre message de candidature",
    "apply.messageTip": "Conseil : Ce message a \u00E9t\u00E9 optimis\u00E9 pour votre profil et le poste vis\u00E9.",
    "apply.cvSubmitted": "CV soumis",
    "apply.cvGenerated": "G\u00E9n\u00E9r\u00E9 \u2022 Optimis\u00E9 pour ce poste",
    "apply.saveForLater": "Enregistrer pour plus tard",
    "apply.applyAndSend": "Postuler et envoyer",

    // Actions List
    "actions.title": "Candidature",
    "actions.searchPlaceholder": "Rechercher par titre de poste...",
    "actions.filterUrgency": "Filtrer par urgence",
    "actions.veryUrgent": "Tr\u00E8s urgent",
    "actions.urgent": "Urgent",
    "actions.normal": "Normal",
    "actions.filterDate": "Filtrer par date",
    "actions.last1Day": "Dernier jour",
    "actions.last3Days": "3 derniers jours",
    "actions.last7Days": "7 derniers jours",
    "actions.allTime": "Tout",
    "actions.applied": "Postul\u00E9",
    "actions.tasks": "T\u00E2ches :",
    "actions.loadMore": "Voir plus",

    // Action Detail
    "actionDetail.backToApps": "Retour aux candidatures",
    "actionDetail.currentStage": "\u00C9tape actuelle",
    "actionDetail.appProgress": "Progression de la candidature",
    "actionDetail.reassurance": "Vous vous en sortez bien. Les choses avancent \u2014 restez concentr\u00E9 sur la suite.",
    "actionDetail.whatToExpect": "\u00C0 quoi s\u2019attendre :",
    "actionDetail.typicalReview": "D\u00E9lai de r\u00E9vision habituel",
    "actionDetail.ghostingRisk": "Risque de ghosting",
    "actionDetail.timeline": "Chronologie de la candidature",
    "actionDetail.inProgress": "En cours",
    "actionDetail.your": "Votre ",
    "actionDetail.stepsForward": "\u00C9tapes pour avancer :",
    "actionDetail.estimatedSalary": "Salaire estim\u00E9 :",
    "actionDetail.sendFollowUp": "Envoyer une relance",

    // Send Follow-up
    "followUp.backToApp": "Retour \u00E0 la candidature",
    "followUp.title": "Envoyer une relance",
    "followUp.role": "Poste",
    "followUp.company": "Entreprise",
    "followUp.stage": "\u00C9tape",
    "followUp.appliedOn": "Postul\u00E9 le",
    "followUp.suggestedMessage": "Message de relance sugg\u00E9r\u00E9",
    "followUp.messageDesc": "Poli, concis et optimis\u00E9 pour votre \u00E9tape actuelle de candidature",
    "followUp.recommendedTiming": "Moment recommand\u00E9",
    "followUp.timingValue": "5\u20137 jours apr\u00E8s la candidature",
    "followUp.note1": "Envoyer une relance augmente les chances de r\u00E9ponse",
    "followUp.note2": "Une relance par \u00E9tape de candidature",
    "followUp.cancel": "Annuler",
    "followUp.editMessage": "Modifier le message",
    "followUp.send": "Envoyer la relance",
    "followUp.sentTitle": "Relance envoy\u00E9e avec succ\u00E8s",
    "followUp.sentDesc": "Votre message de relance a \u00E9t\u00E9 envoy\u00E9. Vous serez notifi\u00E9 en cas de r\u00E9ponse.",
    "followUp.backToDetails": "Retour aux d\u00E9tails de la candidature",
    "followUp.cancelledTitle": "Relance annul\u00E9e",
    "followUp.cancelledDesc": "Vous pourrez envoyer une relance plus tard quand vous serez pr\u00EAt.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const stored = localStorage.getItem('jobtrack_language') as Language | null
    if (stored && (stored === 'en' || stored === 'fr')) {
      setLanguageState(stored)
    }
  }, [])

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('jobtrack_language', lang)
  }, [])

  const t = useCallback((key: string): string => {
    return translations[language][key] || translations['en'][key] || key
  }, [language])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}
